### PR TITLE
TLS connection issues with WordToTFS

### PR DESCRIPTION
**Pull request by norschel**
The pull request is supposed to fix the issue #3 .

### CODE REVIEW

**Comment by vincenormand** [comment]
This PR has been opened for 3 months now.

Can those changes be reviewed, approved and released please ?
WordToTFS is unusable right now... 

Thank you !

**Comment by jsparent** [comment]
+1 for this

**Comment by halllo** [comment]
Please merge it!

**Comment by m-isenmann** [comment]
Changes merged to other [PR](https://github.com/AITGmbH/WordToTFS/pull/12)

**Pull request closed without merging**
